apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-fastapi
  labels:
    app: mlops-fastapi

spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-fastapi

  template:
    metadata:
      labels:
        app: mlops-fastapi

    spec:
      containers:
      - name: mlops-fastapi
        image: 020866158197.dkr.ecr.us-east-1.amazonaws.com/mlops-fastapi:latest
        ports:
        - containerPort: 8000

        env:
        - name: MLFLOW_TRACKING_URI
          valueFrom:
            secretKeyRef:
              name: mlflow-secret
              key: MLFLOW_TRACKING_URI

        - name: MLFLOW_TRACKING_USERNAME
          valueFrom:
            secretKeyRef:
              name: mlflow-secret
              key: MLFLOW_TRACKING_USERNAME

        - name: MLFLOW_TRACKING_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mlflow-secret
              key: MLFLOW_TRACKING_PASSWORD

        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1"


---
apiVersion: v1
kind: Service
metadata:
  name: mlops-fastapi-service

spec:
  type: LoadBalancer
  selector:
    app: mlops-fastapi

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
